# Generated by Django 3.2.18 on 2023-04-20 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='书名')),
                ('author', models.CharField(max_length=100, verbose_name='作者')),
            ],
            options={
                'db_table': 'book',
                'managed': True,
            },
        ),
        migrations.AlterField(
            model_name='student',
            name='student_gender',
            field=models.BooleanField(choices=[('0', '女'), ('1', '男')], default=0, verbose_name='学生性别'),
        ),
    ]
