# Generated by Django 3.2.18 on 2023-04-20 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20230420_1605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='student_gender',
            field=models.CharField(choices=[('0', '女'), ('1', '男')], default=0, max_length=1, verbose_name='学生性别'),
        ),
    ]
